"""empty message

Revision ID: 649e20345a5b
Revises: 78fca35142fe
Create Date: 2021-08-18 00:41:03.601893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "649e20345a5b"
down_revision = "78fca35142fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
