name: Lint

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        run: pip3.9 install black flake8
      
      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true
          flake8_args: "--ignore=W291,E402,W503 --max-line-length=120 --exclude=migrations"
          auto_fix: true
